post_install() {
    echo -e "##########################################"
    echo -e "## Iris was installed in your computer  ##"
    echo -e "##########################################"
    echo -e "##############################################################"
    echo -e "## The iris config files were placed in ~/.iris/config.json ##"
    echo -e "##############################################################"
}

post_upgrade() {
    post_install
}
